server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: @project.name@
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5445}/${DB_NAME:numeration}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  liquibase:
    change-log: classpath:/changelog/db.changelog-master.yaml




